baseURL = 'https://coredump.blog/'
languageCode = 'en-in'
title = 'Coredump'

[module]
[[module.imports]]
path = "github.com/ananthb/jughead"

enableGitInfo = true

# Site parameters
[params]
# Add a logo to your site by placing an image in the assets directory
# and setting the path here. Preferably a square png image.
# logo = "logo.png"

# Choose a colour mode: light, dark, or auto.
colourMode = "auto"
# Choose a theme: default, or ink.
theme = "ink"

# Enable a service worker for offline access.
#
# Set to true to cache pages as they are visited.
serviceWorker = true
# Set to "precache" to cache all pages on first load.
# serviceWorker = "precache"

subtitle = "Mostly programming sometimes philosophy."
description = "Ananth's personal blog about programming."

mainSections = ["blog", "links"]

# Your JSON Resume Registry slug. This is the part of the URL after https://registry.jsonresume.org/.
# Or create a resume.json file in the data directory.
[params.jsonResume]
slug = "ananthb"

# Display a link to the commit that built this site in your footer.
# Requires enableGitInfo = true, and for your website to be public on GitHub.
siteRepo = "ananthb/coredump.blog"  # Site GitHub repository

# Socials
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ananthb"
[[params.social]]
name = "BlueSky"
icon = "bluesky"
url = "https://bsky.app/profile/calculon.tech"
[[params.social]]
name = "Mastodon"
icon = "mastodon"
url = "https://mastodon.social/@ananthbh"
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ananth-bh"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Bad_R_obot"

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
